module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.test.ts', '**/*.spec.ts'],
  testPathIgnorePatterns: [
    '/src/workflow/execution-worker.service.test.ts$',
    '/src/security/api-key.service.test.ts$',
    '/src/telemetry/telemetry.service.test.ts$',
    '/src/advanced/ai-form-builder.service.test.ts$',
    '/src/security/offensive-security.service.test.ts$',
    '/src/security/security-correlation.service.test.ts$',
    '/src/workflow/workflow.service.test.ts$',
    '/src/advanced/advanced-services.test.ts$',
    '/src/security/remediation.service.test.ts$',
    '/src/rules/rule-engine.service.test.ts$',
    '/src/graph/advanced-analytics.service.test.ts$',
    '/src/advanced/advanced-health.service.test.ts$',
    '/src/adapters/adapter-registry.test.ts$',
    '/src/safety/safety-decision.test.ts$',
    '/src/graph/document-processor.service.test.ts$',
    '/src/security/permission-scope.test.ts$',
    '/src/auth/principal.test.ts$',
    '/src/security/security-event.test.ts$',
  ],
  clearMocks: true,
  restoreMocks: true,
};
